feat: icommand_interface
mk3058/42_IRC pull request #20
Opened 2024-01-22 10:34 UTC by minseunk42

2024-01-22 10:37 UTC, mk3058 requested changes

2024-01-22 10:37 UTC, mk3058 commented on Controller/ICommand.hpp
> +        virtual void execute() = 0;
가상함수의 구현부가 추가로 필요할거 같습니다👍

2024-01-22 10:37 UTC, mk3058 commented on Controller/ICommand.hpp
> +    protected:
파생클래스에서 필요한 필드를 미리 선언해 주셨군요 효과적인 방식인것 같습니다😁

2024-01-22 10:39 UTC, mk3058 commented on Controller/ICommand.hpp
> +        std::string msg;
파생클래스에서 필요한 필드를 미리 선언해 주셨군요 효과적인 방식인것 같습니다😁

2024-01-22 12:57 UTC, imjongmin123 commented
interface 활용 적절하네요 굳굳

2024-01-23 07:59 UTC, mk3058 approved these changes
고생하셨습니다~!

2024-01-23 07:59 UTC, mk3058 commented on Controller/ICommand.hpp
> +        virtual bool checkPermit();
checkPermit 메서드가 파생클래스 내부에서만 사용되는 메서드라면 protected 접근제한자  적용을 고려해볼 수 있을거 같습니다!

2024-01-23 07:59 UTC, mk3058 commented on Controller/ICommand.hpp
> +        virtual void execute() = 0;
execute 메서드가 파생클래스 내부에서만 사용되는 메서드라면 protected 접근제한자  적용을 고려해볼 수 있을거 같습니다!

2024-01-23 07:59 UTC, mk3058 commented on main.cpp
> +int main(int ac, char *av[]) {
main 함수가 잘못 포함된거 같습니다

2024-01-23 08:15 UTC, imjongmin123 approved these changes
고생했습니다

2024-01-23 08:15 UTC, merged