Feat/#66
mk3058/42_IRC pull request #70
Opened 2024-01-27 09:09 UTC by imjongmin123

- Server class에서 getter, setter method가 추가되었습니다.
- Server class에서 multiplex, connect method가 수정되었습니다.
- Pass, Nick, UserCmd, Controller, Parameter class가 수정되었습니다.

2024-01-27 10:22 UTC, mk3058 requested changes

2024-01-27 10:22 UTC, mk3058 commented on Controller/Controler.cpp
> +        send(user->getfd(), "PONG :server\r\n", sizeof("PONG :ircserv.com\r\n"), 0);
전송하는 메시지와 글자수 체크를 위해 사용된 메시지가 다른거 같습니다!

2024-01-27 10:22 UTC, mk3058 commented on request/Request.cpp
해당부분 주석 해제해 주셔도 될거 같습니다!

2024-01-27 10:23 UTC, mk3058 requested changes
고생 많으셨습니다!! 코멘트 남긴 부분만 한번 확인해주시면 감사하겠습니다!!

2024-01-28 14:42 UTC, imjongmin123 commented on Controller/Controler.cpp
> +        send(user->getfd(), "PONG :server\r\n", sizeof("PONG :ircserv.com\r\n"), 0);
그러네요 ..! 체크해놓겠습니다

2024-01-29 02:51 UTC, minseunk42 approved these changes

2024-01-29 03:23 UTC, minseunk42 approved these changes

2024-01-29 09:12 UTC, closed without merging